version: '3.1'
services:
  web:
    image: nginx:1.13.5
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./app1:/code/app1
      - ./app2:/code/app2
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php1
      - php2
      - database1
      - database2
  php1:
    image: php:7-fpm
    volumes:
      - ./app1:/code/app1
  database1:
    image: mysql:5.7.19
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "app1"
      MYSQL_PASSWORD: "app1"
      MYSQL_DATABASE: "app1"
  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3000:80
    links:
      - database1:db
  php2:
    image: php:7-fpm
    volumes:
      - ./app2:/code/app2
  database2:
    image: mysql:8.0.3
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "app2"
      MYSQL_PASSWORD: "app2"
      MYSQL_DATABASE: "app2"
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80
    links:
      - database2:db